### ISSUE TITLE
Negative frame positions.

### ISSUE THREAD

**Issue by theoldnewb** [wo1fsea/PyTexturePacker#11]
Hello wo1fsea,

First, thank you for the awesome rectangle/texture packer.

I am not sure if this is bug or not. But, in some plist files the frame key has negative position.
like: {2,-1} The frame sizes seem all correct.
The packer is running with these parameters:

`packer = Packer.create(max_width=2048, max_height=2048, bg_color=0x00ff00ff, trim_mode=True, enable_rotated=True)`

I would expect the "frame" never to be outside the texture page. so, I am kinda puzzled by the {2,-1}
I suspect that it has something to do with the padding/borders etc. 
I left all these values to their defaults.

Kind regards,
theoldnewb

Here is part of the plist:
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>frames</key>
        <dict>
                <key>0044.png</key>
                <dict>
                        <key>frame</key>
                        <string>{{2,-1},{462,514}}</string>
                        <key>offset</key>
                        <string>{-26,21}</string>
                        <key>rotated</key>
                        <true/>
                        <key>sourceColorRect</key>
                        <string>{{255,234},{462,514}}</string>
                        <key>sourceSize</key>
                        <string>{1024,1024}</string>
                </dict>
                <key>0045.png</key>
                <dict>
                        <key>frame</key>
                        <string>{{450,463},{444,510}}</string>
                        <key>offset</key>
                        <string>{-14,23}</string>
                        <key>rotated</key>
                        <false/>
                        <key>sourceColorRect</key>
                        <string>{{276,234},{444,510}}</string>
                        <key>sourceSize</key>
                        <string>{1024,1024}</string>
                </dict>
`
![0044](https://user-images.githubusercontent.com/58051505/78987498-7f240300-7b2e-11ea-9a25-d88fb1aa1c1d.png)
![atlas_9](https://user-images.githubusercontent.com/58051505/78987524-8c40f200-7b2e-11ea-9d6a-a9e0fae01991.png)
[atlas_9.txt](https://github.com/wo1fsea/PyTexturePacker/files/4461308/atlas_9.txt)

**Comment by theoldnewb** [comment]
Somehow the attachments were not added properly...
![atlas_9](https://user-images.githubusercontent.com/58051505/78987958-d9719380-7b2f-11ea-9d30-5eed6b70c1f2.png)

The single image:
![0044](https://user-images.githubusercontent.com/58051505/78988001-fd34d980-7b2f-11ea-871d-1d617d78a9fb.png)

The plist file:
[atlas_9.txt](https://github.com/wo1fsea/PyTexturePacker/files/4461340/atlas_9.txt)

**Comment by wo1fsea** [comment]
> Hello wo1fsea,
> 
> First, thank you for the awesome rectangle/texture packer.
> 
> I am not sure if this is bug or not. But, in some plist files the frame key has negative position.
> like: {2,-1} The frame sizes seem all correct.
> The packer is running with these parameters:
> 
> `packer = Packer.create(max_width=2048, max_height=2048, bg_color=0x00ff00ff, trim_mode=True, enable_rotated=True)`
> 
> I would expect the "frame" never to be outside the texture page. so, I am kinda puzzled by the {2,-1}
> I suspect that it has something to do with the padding/borders etc.
> I left all these values to their defaults.
> 
> Kind regards,
> theoldnewb
> 
> Here is part of the plist:
> `
> 
> frames 0044.png frame {{2,-1},{462,514}} offset {-26,21} rotated sourceColorRect {{255,234},{462,514}} sourceSize {1024,1024} 0045.png frame {{450,463},{444,510}} offset {-14,23} rotated sourceColorRect {{276,234},{444,510}} sourceSize {1024,1024} ` ![0044](https://user-images.githubusercontent.com/58051505/78987498-7f240300-7b2e-11ea-9a25-d88fb1aa1c1d.png) ![atlas_9](https://user-images.githubusercontent.com/58051505/78987524-8c40f200-7b2e-11ea-9d6a-a9e0fae01991.png) [atlas_9.txt](https://github.com/wo1fsea/PyTexturePacker/files/4461308/atlas_9.txt)

Thanks for using this module.
In your case, it's not a bug. The "frame" is outside the texture page, because of the trim_mode parameter. When trim_mode is not 0, it will remove transparent pixels from border, so the transparent pixels removed will be outside the atlas texture.
