### ISSUE TITLE
extrude option missed

### ISSUE THREAD

**Issue by kolobok55** [wo1fsea/PyTexturePacker#12]
Hi, I installed the library pip install PyTexturePacker option
and have last version:
pip show PyTexturePacker
Name: PyTexturePacker
Version: 1.0.1
Summary: an package to create sprite sheets or sprite atlases
Home-page: https://github.com/wo1fsea/PyTexturePacker
Author: Quanyong Huang
Author-email: quanyongh@foxmail.com
License: MIT
Location: c:\users\*****\appdata\local\programs\python\python38\lib\site-packages
Requires: Pillow
Required-by:
But, when use extrude option have this error:

Traceback (most recent call last):
  File "d:/PROJECTS/PYTHON/printncutpacker/printncutpacker.py", line 133, in <module>
    packer = Packer.create(max_width=4096, max_height=2048, bg_color=0xffffff00, extrude=10 )
  File "C:\Users\Felix\AppData\Local\Programs\Python\Python38\lib\site-packages\PyTexturePacker\Packer.py", line 27, in create
    return packer_type(*args, **kwargs)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python38\lib\site-packages\PyTexturePacker\MaxRectsPacker\MaxRectsPacker.py", line 28, in __init__
    super(MaxRectsPacker, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'extrude'

my code:
`
<...>
from PyTexturePacker import Packer

\# create a MaxRectsBinPacker
packer = Packer.create(max_width=4096, max_height=2048, bg_color=0xffffff00, extrude=10 )
\# pack texture images under directory test_case and name the output images as test_case.
\# %d in output file name test_case%d is a placeholder, which is a multipack index, starting with 0.
packer.pack( path_back, "images%d", path )
`

`
class PackerInterface has init without "extrude" option
class PackerInterface(object):
    """
    interface of packer
    """
    ATLAS_TYPE = AtlasInterface

    def __init__(self, bg_color=0x00000000, texture_format=".png", max_width=4096, max_height=4096, enable_rotated=True,
                 force_square=False, border_padding=2, shape_padding=2, inner_padding=0, trim_mode=0,
                 reduce_border_artifacts=False):
`

in release zip 1.0.1 version option "extrude" missed

**Comment by wo1fsea** [comment]
oops! 
sorry, it seems that i have forgot to release a new version to pip for the new parameter.
try to use the master branch on github, i will fix the pip version problem soon.
=。=

**Comment by wo1fsea** [comment]
New version on pip has been released!
thx 4 using.
