### ISSUE TITLE
Hangs or slows way down when packing > 1000 images

### ISSUE THREAD

**Issue by theahura** [wo1fsea/PyTexturePacker#17]
Thanks for this great library!

Unfortunately the library seems to become unusably slow once you go over 1000 images. I have a set of ~4000 images that I want to pack. I added some print statements in the library to see where the slowdown was, looks like its mostly in the _pack() call in MaxRectsPacker. Specifically, it gets stuck in the loop over the image_rect_list at around 1350 images. 

Are there some settings that can be used to make this an approximate packing, so that it can move faster?

**Comment by wo1fsea** [comment]
Thanks for using.
 To make this an approximate packing, you can use TYPE_GUILLOTINE_PACK.
for example

`packer = Packer.create(Packer.TYPE_GUILLOTINE_PACK , max_width=2048, max_height=2048, bg_color=0xffffff00)`
