### ISSUE TITLE
Simple and Fast border artefact reduction method

### ISSUE THREAD

**Issue by newnon** [wo1fsea/PyTexturePacker#6]
i'm not so strong in python, but there is very simple method for border artefact reduction, you just need to copy one border pixel outside picture. 
Example: you have picture 10x10 pixels. 
1. add one empty pixel on every side you will get 12x12 pixels image
2. copy every x=1 pixel to x=0 pixel
copy every x=10 pixel to x=11 pixel
copy every y=1 pixel to y=0 pixel
copy every y=10 pixel to y=11 pixel
you can use for PIL functions for this
3. draw image in atlas but reduce size back to original 

I use this method in all my projects it give good image quality

**Comment by wo1fsea** [comment]
thx 4 your issue
the method you proposed is for rectangle images without transparency
a similar approach is used in this project, which is called "Alpha bleeding"

"Transparent pixels get color of nearest solid pixel. These color values can reduce artifacts around sprites and remove dark halos at transparent borders."

i got an example  here

Original image:
![image](https://user-images.githubusercontent.com/1271101/47831806-19760800-ddcd-11e8-801a-3be085ca04a5.png)

Original image after alpha-remove
![image](https://user-images.githubusercontent.com/1271101/47831769-f51a2b80-ddcc-11e8-931f-6ef7a3c20288.png)

Original image after alpha-bleeding and alpha-remove
![image](https://user-images.githubusercontent.com/1271101/47831755-eaf82d00-ddcc-11e8-908a-6e697084eb70.png)
